#!/bin/bash

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin

# 设置环境变量
RPATH=`realpath $0 | xargs dirname`

# 设置服务名称
SVRNAME="ss-server"
SVRBIN=/usr/bin/${SVRNAME}

USAGE="Usage: $0 {start|stop|restart}"

PARAMS="/opt/script/ss_libev_server.json"
DAEMON="start-stop-daemon --start --background --pidfile /tmp/${SVRNAME}.pid --exec $SVRBIN -- -c $PARAMS"

do_start()
{
    echo $DAEMON
    $DAEMON
    echo "started $SVRNAME service"
}

do_stop()
{
    ps -ef | grep  "$SVRNAME" | grep -v "grep" | awk '{print $2}' | while read pid
    do
	echo "PID:" $pid
        kill -9 $pid
    done
    echo "stopped $SVRNAME service"
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart)
        do_stop
        sleep 1s
        do_start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
