#!/bin/sh

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin

# 设置环境变量
RPATH=`realpath $0 | xargs dirname`

# 设置服务名称
SVRNAME="trojan"
SVRBIN=/usr/local/sbin/${SVRNAME}

USAGE="Usage: $0 {start|stop|restart}"
if [[ $# -ne 1 ]]; then
	echo $USAGE
	exit 1
fi

SVRCONF="/opt/script/trojan_server.json"
DAEMON="start-stop-daemon --start -m --exec $SVRBIN --pidfile /tmp/${SVRNAME}.pid  --background -- -c $SVRCONF"
if [[ ! -e $SVRCONF ]]; then
	echo "$SVRCONF is not exist"
	exit 1
fi

do_start()
{
    echo $DAEMON
    $DAEMON
    echo "started $SVRNAME service"
}

do_stop()
{
    ps -ef | grep  "trojan_server" | grep -v "grep" | awk '{print $2}' | while read pid
    do
	echo "PID:" $pid
        kill -9 $pid
    done
    echo "stopped $SVRNAME service"
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart)
        do_stop
        sleep 1s
        do_start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
